import "core-js/stable";
import "regenerator-runtime/runtime";
import "@ungap/custom-elements";
import "custom-event-polyfill";
import "formdata-polyfill";
import "abortcontroller-polyfill/dist/abortcontroller-polyfill-only";
import "whatwg-fetch";
import "intersection-observer";
import "@stimulus/polyfills";
